# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MLflow metrics via custom exporter
  - job_name: 'mlflow-exporter'
    static_configs:
      - targets: ['mlflow-exporter:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Car Price Prediction metrics via custom exporter
  - job_name: 'car-price-metrics-exporter'
    static_configs:
      - targets: ['car-price-metrics-exporter:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # FastAPI application metrics
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['fastapi-app:8005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # MinIO metrics - disabled due to authentication issues
  # - job_name: 'minio'
  #   static_configs:
  #     - targets: ['minio:9000']
  #   metrics_path: '/minio/v2/metrics'
  #   scrape_interval: 30s
  #   scheme: http
  #   # MinIO requires AWS4-HMAC-SHA256 signature which is complex to configure

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
